// 课程体系数据 —— 4 模块 / 20 门课
// 所有 resources/papers URL 均经过 WebFetch 实际核验(2026-05-26);
// 全部为开源/免费合法资源(官方课程、作者免费书、开源教材、arXiv、CC 授权);
// 原版权书已替换为同主题的开源/免费替代。前端对 url:null 仍兼容(.nolink 灰态)。

const MODULES = [
  {
    id: "m1",
    code: "M01",
    zh: "数理基础",
    en: "Mathematical Foundations",
    tagline: "把 AI 的语法学会,才能听懂它说什么。",
    description:
      "线性代数 · 多元微积分 · 概率统计 · 信息论。重点不是做题,而是把每一个公式翻译成几何与计算图上的直觉。",
    weeks: "22 ~ 28 周",
    credits: 28,
    accent: "primary",
  },
  {
    id: "m2",
    code: "M02",
    zh: "编程与系统",
    en: "Programming & Systems",
    tagline: "模型不只是数学,它在物理世界里跑。",
    description:
      "算法、数据结构、并行与分布式、GPU 与 ML 系统、MLOps。构建从单机到集群、再到生产环境跑模型的全栈工程能力。",
    weeks: "25 ~ 32 周",
    credits: 34,
    accent: "primary",
  },
  {
    id: "m3",
    code: "M03",
    zh: "机器学习与深度学习",
    en: "Machine Learning & Deep Learning",
    tagline: "核心引擎:从感知机到扩散模型的全部肌肉。",
    description:
      "经典机器学习、深度学习、强化学习、概率图模型、生成式 AI。每门课对应一类范式,论文阅读与复现是主线。",
    weeks: "28 ~ 36 周",
    credits: 39,
    accent: "primary",
  },
  {
    id: "m4",
    code: "M04",
    zh: "前沿与应用",
    en: "Frontiers & Applications",
    tagline: "把武器装上,走进真实的研究现场。",
    description:
      "NLP、CV、大语言模型、AI 安全与对齐、大模型应用工程、研究方法与 Capstone。读 2018-2025 的关键论文,做端到端的项目。",
    weeks: "30 ~ 40 周",
    credits: 43,
    accent: "accent",
  },
];

const COURSES = [
  // ============ Module 1: 数理基础 ============
  {
    id: "c101",
    code: "CS-101",
    moduleId: "m1",
    zh: "线性代数",
    en: "Linear Algebra",
    credits: 7,
    weeks: 6,
    prereq: [],
    tag: "必修",
    goal:
      "把矩阵从「数表」升级为「线性变换」,理解特征分解、SVD、伪逆、正交投影背后的几何与算法。",
    outline: [
      "向量空间 · 子空间 · 基与维度",
      "线性变换的四个基本子空间",
      "特征值 · 特征向量 · 谱定理",
      "SVD 与低秩近似",
      "正定矩阵与二次型",
      "数值稳定性与条件数",
    ],
    resources: [
      { type: "video", title: "MIT 18.06 — Gilbert Strang", url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/" },
      { type: "book",  title: "Mathematics for Machine Learning (Ch.2-4)", url: "https://mml-book.github.io/" },
      { type: "video", title: "MIT 18.065 — Matrix Methods (Strang)", url: "https://ocw.mit.edu/courses/18-065-matrix-methods-in-data-analysis-signal-processing-and-machine-learning-spring-2018/" },
      { type: "book",  title: "Introduction to Applied Linear Algebra (VMLS) · Boyd & Vandenberghe", url: "https://web.stanford.edu/~boyd/vmls/" },
    ],
    papers: [
      { title: "Singular Value Decomposition (SVD) — 几何直觉详解", venue: "Gregory Gundersen, 2018", url: "https://gregorygundersen.com/blog/2018/12/10/svd/" },
    ],
    assignments: [
      "手写实现 PCA 与 SVD,并在 MNIST 上对比 sklearn",
      "推导并实现最小二乘 normal equation vs QR 分解",
      "用 SVD 做图像压缩,可视化奇异值衰减",
    ],
    checklist: [
      "能不查公式写出 SVD 的几何解释",
      "解释为什么 PCA 等价于协方差矩阵的特征分解",
      "知道何时该用 LU / QR / Cholesky / SVD",
    ],
  },
  {
    id: "c102",
    code: "CS-102",
    moduleId: "m1",
    zh: "多元微积分与最优化",
    en: "Multivariate Calculus & Optimization",
    credits: 7,
    weeks: 6,
    prereq: ["c101"],
    tag: "必修",
    goal:
      "梯度 · 雅可比 · Hessian 的真正含义;凸优化基本理论与一阶/二阶方法的工程取舍。",
    outline: [
      "多元链式法则与反向传播的等价性",
      "凸集 · 凸函数 · 凸优化基本性质",
      "梯度下降族:SGD / Momentum / Adam",
      "拉格朗日对偶与 KKT 条件",
      "牛顿法 · 拟牛顿 · L-BFGS",
      "约束优化与投影梯度",
    ],
    resources: [
      { type: "video", title: "Stanford EE364A — Boyd Convex Optimization", url: "https://web.stanford.edu/class/ee364a/" },
      { type: "book",  title: "Convex Optimization · Boyd & Vandenberghe", url: "https://web.stanford.edu/~boyd/cvxbook/" },
      { type: "video", title: "MIT 18.02 — Multivariable Calculus", url: "https://ocw.mit.edu/courses/18-02-multivariable-calculus-fall-2007/" },
      { type: "book",  title: "Mathematics for Machine Learning (Ch.5-7)", url: "https://mml-book.github.io/" },
    ],
    papers: [
      { title: "Adam: A Method for Stochastic Optimization", venue: "ICLR 2015", url: "https://arxiv.org/abs/1412.6980" },
      { title: "An Overview of Gradient Descent Optimization Algorithms", venue: "Ruder, 2016", url: "https://arxiv.org/abs/1609.04747" },
    ],
    assignments: [
      "用 numpy 从零实现反向传播(标量、向量、张量三个版本)",
      "实现并对比 SGD / Momentum / Adam 在 Rosenbrock 上的轨迹",
      "在凸 QP 上用 CVXPY 求解并验证 KKT 条件",
    ],
    checklist: [
      "看到任何 loss 函数,能徒手画出梯度场",
      "解释 Adam 的偏置修正项为何存在",
      "能判断一个优化问题是否凸",
    ],
  },
  {
    id: "c103",
    code: "CS-103",
    moduleId: "m1",
    zh: "概率论与数理统计",
    en: "Probability & Mathematical Statistics",
    credits: 7,
    weeks: 6,
    prereq: ["c101"],
    tag: "必修",
    goal: "测度直觉、极大似然、贝叶斯推断、集中不等式——为后面 ML 提供概率语言。",
    outline: [
      "概率空间 · 随机变量 · 期望与方差",
      "常见分布族与共轭先验",
      "极大似然 · MAP · 贝叶斯",
      "EM 算法",
      "集中不等式:Markov / Chebyshev / Hoeffding",
      "假设检验 · Bootstrap",
    ],
    resources: [
      { type: "video", title: "MIT RES.6-012 — Introduction to Probability (Tsitsiklis)", url: "https://ocw.mit.edu/courses/res-6-012-introduction-to-probability-spring-2018/" },
      { type: "video", title: "MIT 18.650 — Statistics for Applications (Rigollet)", url: "https://ocw.mit.edu/courses/18-650-statistics-for-applications-fall-2016/" },
      { type: "video", title: "Seeing Theory — Brown University (交互可视化)", url: "https://seeing-theory.brown.edu/" },
      { type: "book",  title: "Mathematics for Machine Learning (Ch.6)", url: "https://mml-book.github.io/" },
      { type: "book",  title: "Think Stats (2nd ed.) · Allen Downey (开源)", url: "https://greenteapress.com/thinkstats2/thinkstats2.pdf" },
    ],
    papers: [
      { title: "Variational Inference: A Review for Statisticians", venue: "JASA 2017", url: "https://arxiv.org/abs/1601.00670" },
    ],
    assignments: [
      "推导 GMM 的 EM 更新并在合成数据上实现",
      "Bootstrap 实现 95% 置信区间并与解析解对比",
    ],
    checklist: [
      "区分频率派与贝叶斯派在「参数」上的语义差异",
      "能写出 EM 的 E 步与 M 步的一般形式",
    ],
  },
  {
    id: "c104",
    code: "CS-104",
    moduleId: "m1",
    zh: "信息论",
    en: "Information Theory",
    credits: 7,
    weeks: 5,
    prereq: ["c103"],
    tag: "选修",
    goal: "熵、互信息、KL 散度——理解为什么交叉熵是损失函数的默认选项,为 VAE 与扩散模型打基础。",
    outline: [
      "熵、条件熵、联合熵与链式法则",
      "互信息与数据处理不等式",
      "KL 散度与 Jensen 不等式",
      "信道容量与信道编码定理(Shannon 第二定理)",
      "无损压缩:Huffman / 算术编码 / Lempel-Ziv",
      "率失真理论与有损压缩下界",
    ],
    resources: [
      { type: "video", title: "MIT 6.441 — Information Theory", url: "https://ocw.mit.edu/courses/6-441-information-theory-spring-2016/" },
      { type: "book",  title: "MIT 6.441 Information Theory — Lecture Notes (Polyanskiy & Wu)", url: "https://ocw.mit.edu/courses/6-441-information-theory-spring-2016/pages/lecture-notes/" },
    ],
    papers: [
      { title: "A Mathematical Theory of Communication", venue: "Shannon, 1948", url: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf" },
    ],
    assignments: [
      "手推二元对称信道(BSC)的信道容量公式并用 Python 画出 C vs. p 曲线",
      "实现 Huffman 编码器,验证平均码长接近熵下界",
      "用 PyTorch 计算两个高斯分布的 KL 散度,对比解析值",
    ],
    checklist: [
      "能从定义推出 I(X;Y) = H(X) − H(X|Y)",
      "能解释为何 KL 散度非负(Jensen 不等式),及其在 VAE ELBO 中的角色",
      "能写出率失真函数 R(D) 的定义并说明物理意义",
    ],
  },

  // ============ Module 2: 编程与系统 ============
  {
    id: "c201",
    code: "CS-201",
    moduleId: "m2",
    zh: "算法与数据结构",
    en: "Algorithms & Data Structures",
    credits: 7,
    weeks: 6,
    prereq: [],
    tag: "必修",
    goal: "掌握常见算法范式(分治、DP、贪心)及经典图算法,能分析复杂度,理解 NP-完全性归约。",
    outline: [
      "分治:归并排序、快速选择、主定理",
      "动态规划:最优子结构、背包、序列比对",
      "贪心:最小生成树(Kruskal/Prim)、Huffman",
      "图算法:BFS/DFS、Dijkstra、Bellman-Ford、强连通分量",
      "复杂度分析:摊还分析、P/NP/NP-完全",
      "近似算法:顶点覆盖、TSP 2-近似",
    ],
    resources: [
      { type: "video", title: "MIT 6.006 — Introduction to Algorithms", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/" },
      { type: "video", title: "MIT 6.046J — Design and Analysis of Algorithms", url: "https://ocw.mit.edu/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/" },
      { type: "video", title: "Princeton Algorithms (Sedgewick) — Coursera", url: "https://www.coursera.org/learn/algorithms-part1" },
      { type: "book",  title: "Algorithms · Jeff Erickson (免费开源书)", url: "https://jeffe.cs.illinois.edu/teaching/algorithms/" },
    ],
    papers: [],
    assignments: [
      "实现 Dijkstra(优先队列版)并对随机图测试正确性与时间复杂度",
      "用 DP 解 LeetCode 编辑距离(72)并写出状态转移方程推导",
      "证明独立集问题 NP-完全(从 3-SAT 归约)并写出归约函数",
    ],
    checklist: [
      "给出任意递归式能用主定理或递归树分析时间复杂度",
      "能写出 Bellman-Ford 更新规则并解释为何可检测负环",
      "能区分 NP-完全与 NP-难,并举例近似算法的近似比",
    ],
  },
  {
    id: "c202",
    code: "CS-202",
    moduleId: "m2",
    zh: "并行与分布式计算",
    en: "Parallel & Distributed Computing",
    credits: 7,
    weeks: 6,
    prereq: ["c201"],
    tag: "必修",
    goal: "理解多核/GPU/集群并行模型,掌握 CAP 与 Raft,能用 Spark 处理大规模数据,了解分布式训练拓扑。",
    outline: [
      "并行模型:Amdahl 定律、数据并行 vs 任务并行、共享内存 vs 消息传递",
      "CAP 定理与一致性级别(线性一致、最终一致)",
      "MapReduce 编程模型与 Shuffle/Sort",
      "Raft 共识:领导选举、日志复制、安全性",
      "Apache Spark:RDD / DataFrame / Catalyst",
      "分布式 DL 训练:数据并行(AllReduce)、张量并行、流水线并行",
    ],
    resources: [
      { type: "video", title: "MIT 6.5840 (原 6.824) — Distributed Systems", url: "https://pdos.csail.mit.edu/6.824/" },
      { type: "book",  title: "Apache Spark 官方文档", url: "https://spark.apache.org/docs/latest/" },
      { type: "video", title: "MIT 6.852J — Distributed Algorithms", url: "https://ocw.mit.edu/courses/6-852j-distributed-algorithms-fall-2009/" },
    ],
    papers: [
      { title: "MapReduce: Simplified Data Processing on Large Clusters", venue: "OSDI 2004", url: "https://storage.googleapis.com/gweb-research2023-media/pubtools/4449.pdf" },
      { title: "In Search of an Understandable Consensus Algorithm (Raft)", venue: "USENIX ATC 2014", url: "https://raft.github.io/raft.pdf" },
      { title: "Efficient Large-Scale Language Model Training on GPU Clusters (Megatron-LM)", venue: "SC 2021", url: "https://arxiv.org/abs/2104.04473" },
    ],
    assignments: [
      "用 PySpark 实现 PageRank,在 Wikipedia 子图上验证收敛",
      "实现 Raft 领导选举(可参考 MIT 6.5840 Lab),通过分区/重启场景测试",
      "用 PyTorch DDP 训练 ResNet-50,记录 1/2/4 GPU 吞吐量与通信开销",
    ],
    checklist: [
      "能用状态机图解释 Raft 领导选举全流程,包括分裂投票处理",
      "能说明 CAP 中 CP vs AP 在网络分区时的行为差异",
      "能解释 Ring-AllReduce 如何在 N 卡同步梯度,通信复杂度多少",
    ],
  },
  {
    id: "c203",
    code: "CS-203",
    moduleId: "m2",
    zh: "GPU 编程与 CUDA",
    en: "GPU Programming with CUDA",
    credits: 7,
    weeks: 5,
    prereq: ["c201"],
    tag: "选修",
    goal: "从 SM/warp 出发,掌握内存合并访问与共享内存优化;手写 tiled GEMM;用 Triton 接入 PyTorch。",
    outline: [
      "GPU 硬件模型:SM、warp、线程块调度、占用率",
      "内存层次:全局 / 共享 / 寄存器,合并访问(coalescing)",
      "GEMM 优化:naive → tiled(共享内存)→ tensor core (wmma)",
      "Triton 编程模型:tile 抽象、autotuning、与 CUDA 对比",
      "异步流与流水线:CUDA streams、cuBLAS/cuDNN 集成",
      "自定义 PyTorch 算子:C++ extension、torch.compile",
    ],
    resources: [
      { type: "book",  title: "NVIDIA CUDA C++ Programming Guide", url: "https://docs.nvidia.com/cuda/cuda-programming-guide/" },
      { type: "video", title: "GPU MODE Lectures", url: "https://github.com/gpu-mode/lectures" },
      { type: "book",  title: "Triton Language & Compiler", url: "https://github.com/triton-lang/triton" },
      { type: "book",  title: "Programming on Parallel Machines: GPU, Multicore, Clusters · Matloff (免费)", url: "https://heather.cs.ucdavis.edu/parprocbook" },
    ],
    papers: [
      { title: "FlashAttention: Fast and Memory-Efficient Exact Attention", venue: "NeurIPS 2022", url: "https://arxiv.org/abs/2205.14135" },
    ],
    assignments: [
      "用 CUDA C 实现 naive → tiled GEMM,用 nsight 测吞吐量,达到 cuBLAS 70% 性能",
      "用 Triton 实现 softmax kernel,与 PyTorch 原生比较精度与速度",
      "封装自定义 PyTorch C++ extension(fused bias+ReLU),用 autograd 验证梯度",
    ],
    checklist: [
      "能解释 warp divergence 成因及如何避免",
      "能说明 tiled GEMM 中 shared memory 的加载/计算/存储流水及 bank conflict 规避",
      "给定寄存器和 shared memory 用量,能估算 SM 占用率",
    ],
  },
  {
    id: "c204",
    code: "CS-204",
    moduleId: "m2",
    zh: "机器学习系统",
    en: "Machine Learning Systems",
    credits: 7,
    weeks: 6,
    prereq: ["c202", "c203"],
    tag: "必修",
    goal: "从训练到推理的全栈系统观:编译器、调度器、量化、服务。",
    outline: [
      "自动微分:前向/反向模式、计算图、算子融合",
      "图编译器:XLA(HLO)、TVM(Relay/TE/TIR)、torch.compile + Inductor",
      "量化 · 蒸馏 · 剪枝",
      "推理引擎:连续批处理、KV cache、投机解码",
      "vLLM 与 PagedAttention",
      "训练框架对比与 fault tolerance",
    ],
    resources: [
      { type: "video", title: "CMU 10-414/714 — Deep Learning Systems", url: "https://dlsyscourse.org" },
      { type: "book",  title: "Apache TVM 官方文档", url: "https://tvm.apache.org/docs/" },
      { type: "book",  title: "vLLM 官方网站", url: "https://vllm.ai" },
    ],
    papers: [
      { title: "TVM: An Automated End-to-End Optimizing Compiler for Deep Learning", venue: "OSDI 2018", url: "https://arxiv.org/abs/1802.04799" },
      { title: "Efficient Memory Management for LLM Serving with PagedAttention (vLLM)", venue: "SOSP 2023", url: "https://arxiv.org/abs/2309.06180" },
      { title: "FlashAttention: Fast and Memory-Efficient Exact Attention", venue: "NeurIPS 2022", url: "https://arxiv.org/abs/2205.14135" },
    ],
    assignments: [
      "用 numpy 实现微型自动微分库(参考 dlsyscourse hw0/1),验证 MLP 梯度正确性",
      "用 torch.compile 编译一个 Transformer block,查看 Inductor 生成的 Triton kernel",
      "部署 vLLM 服务 7B 模型,对比有/无 PagedAttention 的吞吐量与显存",
    ],
    checklist: [
      "能画出训练 step 的端到端时间线",
      "能解释 TVM 中 Schedule 与 Compute 分离设计,以及 autoTVM/Ansor 搜索",
      "能解释 KV cache 碎片化及 PagedAttention 如何用分页解决",
    ],
  },
  {
    id: "c205",
    code: "CS-205",
    moduleId: "m2",
    zh: "MLOps 与模型生产化",
    en: "MLOps & Production ML",
    credits: 6,
    weeks: 4,
    prereq: ["c301"],
    tag: "必修",
    goal: "搭建端到端 ML 流水线;掌握数据/模型版本、自动化训练、容器化部署与线上监控,达到 Google MLOps Level-2 成熟度。",
    outline: [
      "数据版本与特征工程流水线(DVC、Feature Store)",
      "实验追踪与模型注册(MLflow、W&B)",
      "训练流水线自动化与超参调优(Kubeflow、Ray Train)",
      "模型打包与容器化部署(Docker、BentoML/Triton、REST/gRPC)",
      "CI/CD for ML:代码 + 数据 + 模型三层测试、GitHub Actions",
      "线上监控与数据漂移检测、再训练触发",
    ],
    resources: [
      { type: "video", title: "Made With ML — MLOps Course", url: "https://madewithml.com/courses/mlops/" },
      { type: "video", title: "Full Stack Deep Learning — LLM Bootcamp", url: "https://fullstackdeeplearning.com/llm-bootcamp/" },
      { type: "book",  title: "Rules of Machine Learning · Google (MLOps 最佳实践)", url: "https://developers.google.com/machine-learning/guides/rules-of-ml/" },
      { type: "book",  title: "Google Cloud — MLOps Whitepaper", url: "https://docs.cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning" },
      { type: "book",  title: "MLflow Documentation", url: "https://mlflow.org/docs/latest/index.html" },
      { type: "book",  title: "Weights & Biases Documentation", url: "https://docs.wandb.ai/guides/" },
      { type: "book",  title: "DVC Documentation", url: "https://doc.dvc.org/" },
    ],
    papers: [],
    assignments: [
      "用 DVC 追踪数据集两个版本,MLflow 记录不同超参实验,生成对比报告",
      "GitHub Actions 流水线:push → 训练 → 评估 → 达标自动注册到 MLflow Model Registry",
      "部署 FastAPI 推理服务,接入 W&B Monitoring 模拟漂移并触发告警",
    ],
    checklist: [
      "能画出 Google MLOps Level-0/1/2 区别,指出自己项目处于哪级",
      "能解释为什么仅代码版本管理不够,DVC 如何用 git-like 语义管理数据/模型",
      "能写出完整 CI/CD for ML 的 GitHub Actions YAML",
    ],
  },

  // ============ Module 3: 机器学习与深度学习 ============
  {
    id: "c301",
    code: "CS-301",
    moduleId: "m3",
    zh: "机器学习",
    en: "Machine Learning",
    credits: 8,
    weeks: 8,
    prereq: ["c102", "c103"],
    tag: "必修",
    goal: "从线性模型到集成方法,建立监督/非监督/半监督的统一视角。",
    outline: [
      "线性 / 逻辑回归 · 正则化",
      "SVM 与核方法",
      "决策树 · 随机森林 · GBDT",
      "聚类与降维",
      "VC 维与泛化理论",
      "特征工程与数据偏差",
    ],
    resources: [
      { type: "video", title: "Stanford CS229 — Andrew Ng", url: "https://cs229.stanford.edu/" },
      { type: "video", title: "Machine Learning Specialization — Andrew Ng (Coursera)", url: "https://www.coursera.org/specializations/machine-learning-introduction" },
      { type: "book",  title: "An Introduction to Statistical Learning (ISLP)", url: "https://www.statlearning.com/" },
      { type: "book",  title: "The Elements of Statistical Learning · Hastie et al.", url: "https://hastie.su.domains/ElemStatLearn/" },
      { type: "book",  title: "scikit-learn User Guide", url: "https://scikit-learn.org/stable/user_guide.html" },
    ],
    papers: [
      { title: "Statistical Modeling: The Two Cultures", venue: "Breiman, 2001", url: "https://projecteuclid.org/journals/statistical-science/volume-16/issue-3/Statistical-Modeling--The-Two-Cultures/10.1214/ss/1009213726.full" },
      { title: "XGBoost: A Scalable Tree Boosting System", venue: "KDD 2016", url: "https://arxiv.org/abs/1603.02754" },
      { title: "Random Forests", venue: "Breiman, 2001", url: "https://www.stat.berkeley.edu/~breiman/randomforest2001.pdf" },
    ],
    assignments: [
      "在 Kaggle 完成一个端到端比赛(银牌目标)",
      "实现 SVM 的 SMO 算法",
      "用 NumPy 从零实现逻辑回归(正规方程 + 梯度下降),与 sklearn 对照",
    ],
    checklist: [
      "能解释 bias-variance tradeoff",
      "看到一个新数据集能给出 baseline 三步走",
      "能解释为何随机森林比单树稳,Boosting 与 Bagging 的本质区别",
    ],
  },
  {
    id: "c302",
    code: "CS-302",
    moduleId: "m3",
    zh: "深度学习",
    en: "Deep Learning",
    credits: 9,
    weeks: 8,
    prereq: ["c301", "c204"],
    tag: "必修",
    goal: "把神经网络看成可微分编程;从 CNN 到 Transformer 的设计哲学,能用 PyTorch 训练并调试。",
    outline: [
      "MLP · 反向传播 · 初始化",
      "卷积神经网络与归纳偏置",
      "RNN / LSTM / GRU",
      "Attention 与 Transformer",
      "正则化:Dropout · BN · LN",
      "迁移学习与微调",
    ],
    resources: [
      { type: "book",  title: "Dive into Deep Learning (d2l.ai)", url: "https://d2l.ai/" },
      { type: "book",  title: "Deep Learning Book · Goodfellow, Bengio, Courville", url: "https://www.deeplearningbook.org/" },
      { type: "video", title: "Practical Deep Learning for Coders · fast.ai", url: "https://course.fast.ai/" },
      { type: "video", title: "Neural Networks: Zero to Hero · Karpathy", url: "https://karpathy.ai/zero-to-hero.html" },
      { type: "book",  title: "PyTorch 官方教程", url: "https://docs.pytorch.org/tutorials/" },
    ],
    papers: [
      { title: "Attention Is All You Need", venue: "NeurIPS 2017", url: "https://arxiv.org/abs/1706.03762" },
      { title: "Deep Residual Learning for Image Recognition (ResNet)", venue: "CVPR 2016", url: "https://arxiv.org/abs/1512.03385" },
      { title: "Batch Normalization", venue: "ICML 2015", url: "https://arxiv.org/abs/1502.03167" },
      { title: "Sequence to Sequence Learning with Neural Networks", venue: "NeurIPS 2014", url: "https://arxiv.org/abs/1409.3215" },
    ],
    assignments: [
      "用 PyTorch 从零实现 MLP 在 MNIST 上训练,手写前/反向传播",
      "复现 ResNet-18 在 CIFAR-10 达到 >93%,对比去掉残差连接的退化",
      "实现字符级 Transformer 解码器,在莎士比亚或中文语料上采样生成",
    ],
    checklist: [
      "能用一段话向非技术朋友解释 attention",
      "知道为什么深网络需要残差连接",
      "能徒手画出 Scaled Dot-Product Attention 计算流程",
    ],
  },
  {
    id: "c303",
    code: "CS-303",
    moduleId: "m3",
    zh: "强化学习",
    en: "Reinforcement Learning",
    credits: 8,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "MDP · 价值函数 · 策略梯度 · 离线 RL · RLHF 的来龙去脉。",
    outline: [
      "MDP 与 Bellman 方程",
      "TD 学习 · Q-learning · SARSA",
      "策略梯度 · A2C · PPO",
      "Actor-Critic 与模型基础 RL",
      "离线 RL · 模仿学习",
      "RLHF 与对齐",
    ],
    resources: [
      { type: "book",  title: "Reinforcement Learning: An Introduction · Sutton & Barto", url: "http://incompleteideas.net/book/RLbook2020.pdf" },
      { type: "video", title: "David Silver RL Course (UCL/DeepMind)", url: "https://davidstarsilver.wordpress.com/teaching/" },
      { type: "video", title: "OpenAI Spinning Up", url: "https://spinningup.openai.com/en/latest/" },
      { type: "video", title: "Berkeley CS285 — Deep RL", url: "https://rail.eecs.berkeley.edu/deeprlcourse/" },
    ],
    papers: [
      { title: "Playing Atari with Deep Reinforcement Learning (DQN)", venue: "Mnih et al., 2013", url: "https://arxiv.org/abs/1312.5602" },
      { title: "Proximal Policy Optimization Algorithms (PPO)", venue: "Schulman et al., 2017", url: "https://arxiv.org/abs/1707.06347" },
      { title: "Asynchronous Methods for Deep RL (A3C)", venue: "ICML 2016", url: "https://arxiv.org/abs/1602.01783" },
      { title: "Mastering Chess and Shogi by Self-Play (AlphaZero)", venue: "Silver et al., 2017", url: "https://arxiv.org/abs/1712.01815" },
      { title: "Training language models to follow instructions (InstructGPT)", venue: "NeurIPS 2022", url: "https://arxiv.org/abs/2203.02155" },
    ],
    assignments: [
      "在 Gymnasium 上跑通 DQN,从 CartPole → LunarLander → Atari Breakout",
      "用 Spinning Up 的 PPO 在 MuJoCo HalfCheetah/Ant 训练连续控制策略",
      "实现 RLHF 简化版:reward model + PPO 微调小型 LM",
    ],
    checklist: [
      "能徒手写出贝尔曼最优方程并证明值迭代收敛",
      "能解释 DQN 中经验回放和目标网络分别解决什么问题",
      "能区分 on-policy(PPO/A2C)与 off-policy(DQN/SAC)的数据使用",
    ],
  },
  {
    id: "c304",
    code: "CS-304",
    moduleId: "m3",
    zh: "概率图模型",
    en: "Probabilistic Graphical Models",
    credits: 7,
    weeks: 6,
    prereq: ["c103"],
    tag: "选修",
    goal: "贝叶斯网络与马尔可夫随机场;精确与近似推断;为 VAE 与现代生成模型打理论底。",
    outline: [
      "有向图(贝叶斯网络):条件独立、d-分离、因式分解",
      "无向图(MRF):团势函数、配分函数、Ising 模型",
      "精确推断:变量消除、Sum-Product、Junction Tree",
      "近似推断:变分推断(ELBO、均场)、MCMC(MH、Gibbs)",
      "隐变量模型与 VAE:EM 算法、变分自编码器推导",
      "结构学习:得分法(BIC)、约束法(PC 算法)",
    ],
    resources: [
      { type: "video", title: "Stanford CS228 — Probabilistic Graphical Models", url: "https://ermongroup.github.io/cs228/" },
      { type: "book",  title: "Stanford CS228 — Course Notes (Kuleshov & Ermon)", url: "https://ermongroup.github.io/cs228-notes/" },
      { type: "book",  title: "Mathematics for Machine Learning (Ch.8 概率建模)", url: "https://mml-book.github.io/" },
    ],
    papers: [
      { title: "Auto-Encoding Variational Bayes (VAE)", venue: "ICLR 2014", url: "https://arxiv.org/abs/1312.6114" },
    ],
    assignments: [
      "手推贝叶斯网络上变量消除的完整计算过程,对比置信传播,分析复杂度",
      "推导均场变分推断 ELBO 更新公式,在 GMM 上代码验证收敛",
      "复现 VAE 训练(编码器/解码器/重参数化),在 MNIST 上可视化隐空间插值",
    ],
    checklist: [
      "给定贝叶斯网络,能立即写出联合概率因式分解并判断条件独立",
      "能推导 ELBO = 重建项 − KL 散度,解释最大化 ELBO 与后验近似的关系",
      "能说明 Gibbs 与 MH 的适用场景差异",
    ],
  },
  {
    id: "c305",
    code: "CS-305",
    moduleId: "m3",
    zh: "生成式 AI:扩散模型与多模态",
    en: "Generative AI",
    credits: 7,
    weeks: 5,
    prereq: ["c302"],
    tag: "必修",
    goal: "GAN/VAE/扩散模型原理,理解 Stable Diffusion 与多模态生成,能用 Diffusers 完成文本引导生成。",
    outline: [
      "生成模型基础:VAE、GAN(极小极大博弈、模式坍塌)",
      "扩散模型:DDPM 前向/反向数学推导、噪声预测网络",
      "DDIM 确定性采样与 Score Matching",
      "Latent Diffusion(LDM)与 Stable Diffusion 全流程",
      "CLIP 视觉-语言对齐与文本条件生成",
      "ControlNet 与多模态控制",
    ],
    resources: [
      { type: "video", title: "Hugging Face Diffusion Models Course", url: "https://huggingface.co/learn/diffusion-course/en/unit0/1" },
      { type: "book",  title: "Lilian Weng — What are Diffusion Models?", url: "https://lilianweng.github.io/posts/2021-07-11-diffusion-models/" },
      { type: "book",  title: "Hugging Face Diffusers Documentation", url: "https://huggingface.co/docs/diffusers/" },
    ],
    papers: [
      { title: "Generative Adversarial Networks", venue: "Goodfellow et al., 2014", url: "https://arxiv.org/abs/1406.2661" },
      { title: "Auto-Encoding Variational Bayes (VAE)", venue: "Kingma & Welling, 2013", url: "https://arxiv.org/abs/1312.6114" },
      { title: "Denoising Diffusion Probabilistic Models (DDPM)", venue: "NeurIPS 2020", url: "https://arxiv.org/abs/2006.11239" },
      { title: "High-Resolution Image Synthesis with Latent Diffusion (Stable Diffusion)", venue: "Rombach et al., 2021", url: "https://arxiv.org/abs/2112.10752" },
      { title: "Learning Transferable Visual Models from Natural Language Supervision (CLIP)", venue: "Radford et al., 2021", url: "https://arxiv.org/abs/2103.00020" },
      { title: "Hierarchical Text-Conditional Image Generation (DALL-E 2)", venue: "Ramesh et al., 2022", url: "https://arxiv.org/abs/2204.06125" },
    ],
    assignments: [
      "从零实现 DDPM(PyTorch)在 MNIST/CIFAR-10 上训练,记录 FID 随步数变化",
      "用 Diffusers 加载 Stable Diffusion,探索 CFG scale、negative prompt、ControlNet",
      "实现条件 GAN(cGAN)与 CycleGAN,与扩散模型在同一数据集 FID 对比",
    ],
    checklist: [
      "能推导 VAE 的 ELBO,解释重参数化技巧必要性",
      "能用公式描述 DDPM 前向加噪与反向去噪",
      "能解释为何 LDM 在潜空间扩散而非像素空间",
    ],
  },

  // ============ Module 4: 前沿与应用 ============
  {
    id: "c401",
    code: "CS-401",
    moduleId: "m4",
    zh: "自然语言处理",
    en: "Natural Language Processing",
    credits: 7,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "从 n-gram 到 BERT 到 LLM:语言建模史与现代任务范式。",
    outline: [
      "分词 · embedding · word2vec / GloVe",
      "序列标注 · 依存解析",
      "Seq2Seq + Attention",
      "Encoder-Decoder 与 BERT 系列(MLM/NSP)",
      "信息抽取 · 问答 · 摘要",
      "评测体系与数据集",
    ],
    resources: [
      { type: "video", title: "Stanford CS224N — NLP with Deep Learning", url: "http://web.stanford.edu/class/cs224n" },
      { type: "video", title: "Hugging Face NLP Course", url: "https://huggingface.co/learn/nlp-course/chapter1/1" },
      { type: "book",  title: "Speech and Language Processing (3rd ed. draft) · Jurafsky & Martin (作者免费)", url: "https://web.stanford.edu/~jurafsky/slp3/" },
    ],
    papers: [
      { title: "Efficient Estimation of Word Representations in Vector Space (word2vec)", venue: "Mikolov et al., 2013", url: "https://arxiv.org/abs/1301.3781" },
      { title: "Neural Machine Translation by Jointly Learning to Align and Translate (Bahdanau Attention)", venue: "ICLR 2015", url: "https://arxiv.org/abs/1409.0473" },
      { title: "BERT: Pre-training of Deep Bidirectional Transformers", venue: "NAACL 2019", url: "https://arxiv.org/abs/1810.04805" },
    ],
    assignments: [
      "在 SQuAD 上微调 BERT 达到论文水平",
      "实现一个 BPE tokenizer",
      "复现一个基于 Bahdanau Attention 的 seq2seq 翻译模型",
    ],
    checklist: [
      "对比 BPE / WordPiece / SentencePiece",
      "能解释 BERT 的 MLM 与 NSP 目标",
      "能推导 Scaled Dot-Product Attention 的时间复杂度",
    ],
  },
  {
    id: "c402",
    code: "CS-402",
    moduleId: "m4",
    zh: "计算机视觉",
    en: "Computer Vision",
    credits: 7,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "从经典几何到大模型时代;分类、检测、分割、生成的关键里程碑。",
    outline: [
      "图像形成 · 滤波 · 特征",
      "CNN 与现代 backbone(ResNet、EfficientNet)",
      "检测:R-CNN 系列、YOLO、DETR",
      "分割:FCN、U-Net、Mask R-CNN",
      "视频与多视图",
      "Vision Transformer 与 SAM",
    ],
    resources: [
      { type: "video", title: "Stanford CS231N — Deep Learning for Computer Vision", url: "https://cs231n.stanford.edu/" },
      { type: "book",  title: "Dive into Deep Learning — Computer Vision", url: "https://d2l.ai/" },
      { type: "video", title: "Practical Deep Learning for Coders · fast.ai", url: "https://course.fast.ai/" },
    ],
    papers: [
      { title: "Faster R-CNN: Towards Real-Time Object Detection with RPN", venue: "NeurIPS 2015", url: "https://arxiv.org/abs/1506.01497" },
      { title: "Fully Convolutional Networks for Semantic Segmentation (FCN)", venue: "CVPR 2015", url: "https://arxiv.org/abs/1411.4038" },
      { title: "An Image is Worth 16x16 Words (ViT)", venue: "ICLR 2021", url: "https://arxiv.org/abs/2010.11929" },
      { title: "Swin Transformer: Hierarchical ViT using Shifted Windows", venue: "ICCV 2021", url: "https://arxiv.org/abs/2103.14030" },
      { title: "Microsoft COCO: Common Objects in Context", venue: "ECCV 2014", url: "https://arxiv.org/abs/1405.0312" },
    ],
    assignments: [
      "复现 ViT-B/16 在 ImageNet-1k 子集上",
      "在 CIFAR-100 上微调预训练 ResNet-50,记录学习率/frozen layer 对结果的影响",
      "用 torchvision Faster R-CNN 在自定义小数据集上微调,可视化检测框",
    ],
    checklist: [
      "对比 CNN 与 ViT 的归纳偏置",
      "理解为什么 detection 的 NMS 必要",
      "能解释 mAP@0.5 与 mAP@0.5:0.95 计算差异",
    ],
  },
  {
    id: "c403",
    code: "CS-403",
    moduleId: "m4",
    zh: "大语言模型",
    en: "Large Language Models",
    credits: 9,
    weeks: 9,
    prereq: ["c401", "c303"],
    tag: "必修 · 旗舰",
    goal: "Scaling Laws · 预训练 · SFT · RLHF · 推理优化 · Agent。",
    outline: [
      "Scaling Laws 与数据配方",
      "预训练:架构、优化器、并行训练",
      "SFT 与指令数据",
      "RLHF / DPO / 偏好对齐",
      "推理时:KV cache · speculative · MoE",
      "工具使用与 Agent",
      "评测:MMLU · HumanEval · Arena",
    ],
    resources: [
      { type: "video", title: "Neural Networks: Zero to Hero · Karpathy", url: "https://karpathy.ai/zero-to-hero.html" },
      { type: "video", title: "Hugging Face NLP Course (含 LLM 章节)", url: "https://huggingface.co/learn/nlp-course/chapter1/1" },
      { type: "book",  title: "Dive into Deep Learning — Attention/Transformer", url: "https://d2l.ai/" },
    ],
    papers: [
      { title: "Scaling Laws for Neural Language Models", venue: "Kaplan et al., 2020", url: "https://arxiv.org/abs/2001.08361" },
      { title: "Training Compute-Optimal Large Language Models (Chinchilla)", venue: "NeurIPS 2022", url: "https://arxiv.org/abs/2203.15556" },
      { title: "LLaMA: Open and Efficient Foundation Language Models", venue: "Touvron et al., 2023", url: "https://arxiv.org/abs/2302.13971" },
      { title: "Direct Preference Optimization (DPO)", venue: "NeurIPS 2023", url: "https://arxiv.org/abs/2305.18290" },
      { title: "Language Models are Few-Shot Learners (GPT-3)", venue: "NeurIPS 2020", url: "https://arxiv.org/abs/2005.14165" },
      { title: "Training language models to follow instructions (InstructGPT)", venue: "NeurIPS 2022", url: "https://arxiv.org/abs/2203.02155" },
    ],
    assignments: [
      "跟随 Karpathy 从字符级 bigram 到 nanoGPT,在莎士比亚语料上训练",
      "从零预训练 ~100M 的 GPT-like(单 GPU,数小时)",
      "实现带工具调用的 Agent loop",
    ],
    checklist: [
      "能徒手画出 Transformer 一次前向的 FLOPs",
      "解释 Chinchilla 的 token-per-param 比例",
      "知道 RLHF 与 DPO 在目标函数上的等价点",
    ],
  },
  {
    id: "c404",
    code: "CS-404",
    moduleId: "m4",
    zh: "AI 安全与对齐",
    en: "AI Safety & Alignment",
    credits: 5,
    weeks: 5,
    prereq: ["c403"],
    tag: "必修",
    goal: "从可解释性到对抗鲁棒,从对齐税到 scalable oversight,能批判性阅读前沿安全研究。",
    outline: [
      "对齐基础:奖励错配、目标概化失败、Goodhart 定律",
      "RLHF 与 Constitutional AI:人类偏好建模、AI 反馈",
      "机制可解释性:linear probing、superposition、circuits",
      "对抗鲁棒性:对抗样本、越狱攻击、防御现状",
      "Scalable Oversight:debate、amplification、weak-to-strong",
      "评测与治理:MMLU/HELM/WMDP、风险分级、AI 政策",
    ],
    resources: [
      { type: "book",  title: "Fairness and Machine Learning", url: "https://fairmlbook.org" },
      { type: "book",  title: "Transformer Circuits Thread (Anthropic)", url: "https://transformer-circuits.pub" },
      { type: "book",  title: "Distill.pub", url: "https://distill.pub" },
      { type: "book",  title: "Anthropic Research", url: "https://www.anthropic.com/research" },
    ],
    papers: [
      { title: "Concrete Problems in AI Safety", venue: "Amodei et al., 2016", url: "https://arxiv.org/abs/1606.06565" },
      { title: "Constitutional AI: Harmlessness from AI Feedback", venue: "Anthropic, 2022", url: "https://arxiv.org/abs/2212.08073" },
      { title: "Toy Models of Superposition", venue: "Transformer Circuits, 2022", url: "https://transformer-circuits.pub/2022/toy_model/index.html" },
    ],
    assignments: [
      "复现一个 linear probe:在小型 transformer 中间层探测语义属性",
      "对一个开源对话模型执行 5 类越狱攻击,记录成功率",
      "为 Concrete Problems 中一个问题设计最小可复现实验",
    ],
    checklist: [
      "能用例子解释 Goodhart 定律如何在 RLHF 中导致奖励黑客",
      "能解释 superposition 假说及其对机制可解释性的挑战",
      "能对比 debate 与 amplification 两种 scalable oversight 方案",
    ],
  },
  {
    id: "c405",
    code: "CS-405",
    moduleId: "m4",
    zh: "大模型应用工程:RAG · Agent · 微调",
    en: "LLM Application Engineering",
    credits: 7,
    weeks: 5,
    prereq: ["c403", "c205"],
    tag: "必修 · 旗舰",
    goal: "构建生产级 RAG 检索系统与 Agent 工作流,对开源 LLM 做 LoRA/QLoRA 微调,掌握系统级评估。",
    outline: [
      "Prompt 工程系统化:few-shot、CoT、结构化输出、system prompt",
      "RAG 全链路:分块 · embedding · 向量检索 · 重排序 · 生成",
      "Agent 编排:ReAct 循环、工具调用、多 Agent 协作",
      "LoRA/QLoRA 微调:参数高效适配原理、PEFT 库",
      "LLM 评估:ROUGE/BERTScore/LLM-as-Judge、人工评估",
      "LLMOps:提示版本、幻觉监控、cost 追踪",
    ],
    resources: [
      { type: "book",  title: "LangChain Documentation", url: "https://python.langchain.com/docs/introduction/" },
      { type: "book",  title: "LlamaIndex Documentation", url: "https://developers.llamaindex.ai/python/framework/" },
      { type: "book",  title: "Hugging Face PEFT Documentation", url: "https://huggingface.co/docs/peft/index" },
      { type: "book",  title: "Anthropic — Building Effective Agents", url: "https://www.anthropic.com/research/building-effective-agents" },
      { type: "video", title: "Full Stack LLM Bootcamp", url: "https://fullstackdeeplearning.com/llm-bootcamp/" },
    ],
    papers: [
      { title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks (RAG)", venue: "NeurIPS 2020", url: "https://arxiv.org/abs/2005.11401" },
      { title: "ReAct: Synergizing Reasoning and Acting in Language Models", venue: "ICLR 2023", url: "https://arxiv.org/abs/2210.03629" },
      { title: "LoRA: Low-Rank Adaptation of Large Language Models", venue: "ICLR 2022", url: "https://arxiv.org/abs/2106.09685" },
      { title: "QLoRA: Efficient Finetuning of Quantized LLMs", venue: "NeurIPS 2023", url: "https://arxiv.org/abs/2305.14314" },
    ],
    assignments: [
      "为中文文档集合搭建 RAG 问答:分块 → embedding → 向量检索 → 重排 → 生成,用 ROUGE + LLM-as-Judge 评估",
      "用 ReAct 实现能调用搜索 + 计算器工具的 Agent,分析失败案例",
      "用 QLoRA 微调 7B 开源模型,对比微调前后指标,记录显存与训练曲线",
    ],
    checklist: [
      "能解释 RAG 中向量检索与重排各解决什么问题,以及 chunk size 的影响",
      "对比 LoRA 与全参微调的计算量差异,说明 QLoRA 的量化 + LoRA 叠加",
      "能设计 LLM 评估方案,说明何时用自动指标、何时必须人工评估",
    ],
  },
  {
    id: "c406",
    code: "CS-406",
    moduleId: "m4",
    zh: "研究方法与 Capstone",
    en: "Research Methods & Capstone",
    credits: 8,
    weeks: 8,
    prereq: ["c403"],
    tag: "必修 · 实践",
    goal: "高效读论文、复现实验、文献管理、写作,加一个端到端 Capstone 项目并开源。",
    outline: [
      "Keshav 三遍法读论文 · Andrew Ng 读论文方法",
      "Papers with Code / Connected Papers / arXiv 调研流程",
      "Zotero 文献管理与 BibTeX",
      "Capstone:选题 · 数据 · 基线 · 主实验 · 消融",
      "Datasheets for Datasets / Model Cards 文档规范",
      "技术写作:IMRaD 结构 · 答辩 · 开源发布(README、demo)",
    ],
    resources: [
      { type: "book",  title: "arXiv.org", url: "https://arxiv.org" },
      { type: "book",  title: "Distill.pub (写作与可视化范本)", url: "https://distill.pub" },
      { type: "book",  title: "Zotero (文献管理)", url: "https://www.zotero.org" },
      { type: "book",  title: "Connected Papers", url: "https://www.connectedpapers.com" },
      { type: "book",  title: "GitHub (代码托管)", url: "https://github.com" },
    ],
    papers: [
      { title: "Datasheets for Datasets", venue: "Gebru et al., 2018", url: "https://arxiv.org/abs/1803.09010" },
      { title: "Model Cards for Model Reporting", venue: "Mitchell et al., 2019", url: "https://arxiv.org/abs/1810.03993" },
      { title: "Grad-CAM (含官方代码,适合作复现练习)", venue: "Selvaraju et al., 2019", url: "https://arxiv.org/abs/1610.02391" },
    ],
    assignments: [
      "三遍法读 5 篇 arXiv 论文,输出统一笔记表",
      "从 Papers with Code 选一篇复现主实验,记录环境、坑、结果对比",
      "完整 Capstone:选题 → 数据集说明 → 基线 → 主实验 → 消融 → 报告 → 开源仓库(README + Model Card + demo)",
    ],
    checklist: [
      "能 5 分钟完成论文第一遍,判断是否值得深读",
      "复现日志含环境、步骤、结果数值对比与差异分析",
      "第三方按 README 在 10 分钟内能运行 demo",
    ],
  },
];

window.MODULES = MODULES;
window.COURSES = COURSES;
window.TOTAL_CREDITS = COURSES.reduce((s, c) => s + c.credits, 0);
window.TOTAL_WEEKS = COURSES.reduce((s, c) => s + c.weeks, 0);
