// 课程体系数据 —— 4 模块 / 16 课 / 120 学分
// 学分粗略按课程深度分配,讲义/论文为示意性条目

const MODULES = [
  {
    id: "m1",
    code: "M01",
    zh: "数理基础",
    en: "Mathematical Foundations",
    tagline: "把 AI 的语法学会,才能听懂它说什么。",
    description:
      "线性代数 · 多元微积分 · 概率统计 · 信息论。重点不是做题,而是把每一个公式翻译成几何与计算图上的直觉。",
    weeks: "16 ~ 22 周",
    credits: 28,
    accent: "primary",
  },
  {
    id: "m2",
    code: "M02",
    zh: "编程与系统",
    en: "Programming & Systems",
    tagline: "模型不只是数学,它在物理世界里跑。",
    description:
      "算法、数据结构、并行与分布式、GPU 与 MLSys。构建从一台机器到一组集群跑模型的工程能力。",
    weeks: "18 ~ 24 周",
    credits: 28,
    accent: "primary",
  },
  {
    id: "m3",
    code: "M03",
    zh: "机器学习与深度学习",
    en: "Machine Learning & Deep Learning",
    tagline: "核心引擎:从感知机到 Transformer 的全部肌肉。",
    description:
      "经典机器学习、深度学习、强化学习、概率图模型。每门课对应一类范式,论文阅读与复现是主线。",
    weeks: "24 ~ 30 周",
    credits: 36,
    accent: "primary",
  },
  {
    id: "m4",
    code: "M04",
    zh: "前沿与应用",
    en: "Frontiers & Applications",
    tagline: "把武器装上,走进真实的研究现场。",
    description:
      "NLP、CV、大语言模型、AI 安全与对齐。读 2018-2025 的关键论文,做端到端的项目。",
    weeks: "20 ~ 28 周",
    credits: 28,
    accent: "accent",
  },
];

const COURSES = [
  // ============ Module 1 ============
  {
    id: "c101",
    code: "CS-101",
    moduleId: "m1",
    zh: "线性代数",
    en: "Linear Algebra",
    credits: 7,
    weeks: 6,
    prereq: [],
    tag: "必修",
    goal:
      "把矩阵从「数表」升级为「线性变换」,理解特征分解、SVD、伪逆、正交投影背后的几何与算法。",
    outline: [
      "向量空间 · 子空间 · 基与维度",
      "线性变换的四个基本子空间",
      "特征值 · 特征向量 · 谱定理",
      "SVD 与低秩近似",
      "正定矩阵与二次型",
      "数值稳定性与条件数",
    ],
    resources: [
      { type: "video", title: "MIT 18.06 — Gilbert Strang", url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/" },
      { type: "book", title: "Linear Algebra Done Right · Axler", url: "#" },
      { type: "book", title: "Numerical Linear Algebra · Trefethen & Bau", url: "#" },
    ],
    papers: [
      { title: "A Singularly Valuable Decomposition: The SVD of a Matrix", venue: "College Math Journal, 1996", url: "#" },
    ],
    assignments: [
      "手写实现 PCA 与 SVD,并在 MNIST 上对比 sklearn",
      "推导并实现最小二乘 normal equation vs QR 分解",
      "用 SVD 做图像压缩,可视化奇异值衰减",
    ],
    checklist: [
      "能不查公式写出 SVD 的几何解释",
      "解释为什么 PCA 等价于协方差矩阵的特征分解",
      "知道何时该用 LU / QR / Cholesky / SVD",
    ],
  },
  {
    id: "c102",
    code: "CS-102",
    moduleId: "m1",
    zh: "多元微积分与最优化",
    en: "Multivariate Calculus & Optimization",
    credits: 7,
    weeks: 6,
    prereq: ["c101"],
    tag: "必修",
    goal:
      "梯度 · 雅可比 · Hessian 的真正含义;凸优化基本理论与一阶/二阶方法的工程取舍。",
    outline: [
      "多元链式法则与反向传播的等价性",
      "凸集 · 凸函数 · 凸优化基本性质",
      "梯度下降族:SGD / Momentum / Adam",
      "拉格朗日对偶与 KKT 条件",
      "牛顿法 · 拟牛顿 · L-BFGS",
      "约束优化与投影梯度",
    ],
    resources: [
      { type: "video", title: "Stanford EE364A — Boyd", url: "https://web.stanford.edu/class/ee364a/" },
      { type: "book", title: "Convex Optimization · Boyd & Vandenberghe", url: "#" },
    ],
    papers: [
      { title: "Adam: A Method for Stochastic Optimization", venue: "ICLR 2015", url: "#" },
      { title: "On the importance of initialization and momentum in deep learning", venue: "ICML 2013", url: "#" },
    ],
    assignments: [
      "用 numpy 从零实现反向传播(标量、向量、张量三个版本)",
      "实现并对比 SGD / Momentum / Adam 在 Rosenbrock 上的轨迹",
      "在凸 QP 上用 CVXPY 求解并验证 KKT 条件",
    ],
    checklist: [
      "看到任何 loss 函数,能徒手画出梯度场",
      "解释 Adam 的偏置修正项为何存在",
      "能判断一个优化问题是否凸",
    ],
  },
  {
    id: "c103",
    code: "CS-103",
    moduleId: "m1",
    zh: "概率论与数理统计",
    en: "Probability & Mathematical Statistics",
    credits: 7,
    weeks: 6,
    prereq: ["c101"],
    tag: "必修",
    goal: "测度直觉、极大似然、贝叶斯推断、集中不等式——为后面 ML 提供概率语言。",
    outline: [
      "概率空间 · 随机变量 · 期望与方差",
      "常见分布族与共轭先验",
      "极大似然 · MAP · 贝叶斯",
      "EM 算法",
      "集中不等式:Markov / Chebyshev / Hoeffding",
      "假设检验 · Bootstrap",
    ],
    resources: [
      { type: "book", title: "All of Statistics · Wasserman", url: "#" },
      { type: "video", title: "Harvard Stat 110 — Joe Blitzstein", url: "https://projects.iq.harvard.edu/stat110" },
    ],
    papers: [
      { title: "Variational Inference: A Review for Statisticians", venue: "JASA 2017", url: "#" },
    ],
    assignments: [
      "推导 GMM 的 EM 更新并在合成数据上实现",
      "Bootstrap 实现 95% 置信区间并与解析解对比",
    ],
    checklist: [
      "区分频率派与贝叶斯派在「参数」上的语义差异",
      "能写出 EM 的 E 步与 M 步的一般形式",
    ],
  },
  {
    id: "c104",
    code: "CS-104",
    moduleId: "m1",
    zh: "信息论基础",
    en: "Information Theory",
    credits: 7,
    weeks: 5,
    prereq: ["c103"],
    tag: "选修",
    goal: "熵、互信息、KL 散度——理解为什么交叉熵是损失函数的默认选项。",
    outline: ["熵与条件熵", "互信息与数据处理不等式", "KL 散度 · JS 散度", "信道容量", "率失真理论"],
    resources: [
      { type: "book", title: "Elements of Information Theory · Cover & Thomas", url: "#" },
    ],
    papers: [
      { title: "A Mathematical Theory of Communication", venue: "Shannon, 1948", url: "#" },
    ],
    assignments: ["实现并比较 KL / JS / Wasserstein 三种散度在高斯混合上的行为"],
    checklist: ["能解释为什么 KL 散度不对称", "看懂 VAE 中 ELBO 的每一项"],
  },

  // ============ Module 2 ============
  {
    id: "c201",
    code: "CS-201",
    moduleId: "m2",
    zh: "算法与数据结构",
    en: "Algorithms & Data Structures",
    credits: 7,
    weeks: 6,
    prereq: [],
    tag: "必修",
    goal: "建立算法分析与设计的直觉;熟练实现常见数据结构与图算法。",
    outline: ["分治 · 动态规划 · 贪心", "图算法", "随机化算法", "NP-完全性", "近似算法"],
    resources: [
      { type: "book", title: "CLRS · Introduction to Algorithms", url: "#" },
      { type: "video", title: "MIT 6.006 / 6.046", url: "https://ocw.mit.edu/" },
    ],
    papers: [],
    assignments: ["在 LeetCode/Codeforces 完成指定 60 题清单", "实现一个 mini graph DB"],
    checklist: ["能现场推导任意 DP 的状态转移", "能判断一个问题是否在 P / NP"],
  },
  {
    id: "c202",
    code: "CS-202",
    moduleId: "m2",
    zh: "并行与分布式计算",
    en: "Parallel & Distributed Computing",
    credits: 7,
    weeks: 6,
    prereq: ["c201"],
    tag: "必修",
    goal: "理解多核、GPU、集群三层并行;一致性、容错、调度的工程取舍。",
    outline: [
      "线程模型与锁",
      "MPI / Ray / Spark",
      "CAP / 一致性协议",
      "MapReduce 与 dataflow",
      "分布式训练拓扑",
    ],
    resources: [
      { type: "video", title: "MIT 6.824 — Distributed Systems", url: "https://pdos.csail.mit.edu/6.824/" },
    ],
    papers: [
      { title: "MapReduce: Simplified Data Processing on Large Clusters", venue: "OSDI 2004", url: "#" },
      { title: "In Search of an Understandable Consensus Algorithm (Raft)", venue: "USENIX ATC 2014", url: "#" },
    ],
    assignments: ["用 Raft 实现一个 KV store", "用 Ray 跑分布式 hyperparameter search"],
    checklist: ["能口述 Raft 选主流程", "知道何时数据并行/模型并行/流水并行"],
  },
  {
    id: "c203",
    code: "CS-203",
    moduleId: "m2",
    zh: "GPU 编程与 CUDA",
    en: "GPU Programming with CUDA",
    credits: 7,
    weeks: 5,
    prereq: ["c201"],
    tag: "选修",
    goal: "从内存层次到 warp 调度,亲手写算子,看懂 PyTorch 底层。",
    outline: [
      "GPU 架构 · SM · warp",
      "内存层次与 coalescing",
      "矩阵乘法优化:naive → tiled → tensor core",
      "Triton 与 CUDA C 对比",
      "自定义 PyTorch 算子",
    ],
    resources: [
      { type: "book", title: "Programming Massively Parallel Processors · Kirk & Hwu", url: "#" },
      { type: "video", title: "GPU MODE Lecture Series", url: "#" },
    ],
    papers: [
      { title: "FlashAttention: Fast and Memory-Efficient Exact Attention", venue: "NeurIPS 2022", url: "#" },
    ],
    assignments: ["手写 GEMM,达到 cuBLAS 70% 性能", "用 Triton 实现 fused softmax"],
    checklist: ["能解释为何 FlashAttention 不算损失精度", "看懂 nsight 的 timeline"],
  },
  {
    id: "c204",
    code: "CS-204",
    moduleId: "m2",
    zh: "机器学习系统",
    en: "Machine Learning Systems",
    credits: 7,
    weeks: 6,
    prereq: ["c202", "c203"],
    tag: "必修",
    goal: "从训练到推理的全栈系统观:编译器、调度器、量化、服务。",
    outline: [
      "自动微分系统",
      "图编译器:XLA · TVM · Inductor",
      "量化 · 蒸馏 · 剪枝",
      "推理引擎与 KV cache",
      "训练框架对比",
    ],
    resources: [
      { type: "video", title: "CMU 10-414/714 Deep Learning Systems", url: "https://dlsyscourse.org/" },
    ],
    papers: [
      { title: "TVM: An Automated End-to-End Optimizing Compiler for Deep Learning", venue: "OSDI 2018", url: "#" },
      { title: "Efficient Memory Management for LLM Serving with PagedAttention (vLLM)", venue: "SOSP 2023", url: "#" },
    ],
    assignments: ["实现一个 mini autograd 引擎", "在单卡上把 13B 模型推理跑起来"],
    checklist: ["能画出训练 step 的端到端时间线", "理解为何 KV cache 是显存瓶颈"],
  },

  // ============ Module 3 ============
  {
    id: "c301",
    code: "CS-301",
    moduleId: "m3",
    zh: "机器学习",
    en: "Machine Learning",
    credits: 8,
    weeks: 8,
    prereq: ["c102", "c103"],
    tag: "必修",
    goal: "从线性模型到集成方法,建立监督/非监督/半监督的统一视角。",
    outline: [
      "线性 / 逻辑回归 · 正则化",
      "SVM 与核方法",
      "决策树 · 随机森林 · GBDT",
      "聚类与降维",
      "VC 维与泛化理论",
      "特征工程与数据偏差",
    ],
    resources: [
      { type: "book", title: "Pattern Recognition and Machine Learning · Bishop", url: "#" },
      { type: "book", title: "The Elements of Statistical Learning · Hastie et al.", url: "#" },
      { type: "video", title: "Stanford CS229 — Andrew Ng", url: "https://cs229.stanford.edu/" },
    ],
    papers: [
      { title: "Random Forests", venue: "Breiman, 2001", url: "#" },
      { title: "XGBoost: A Scalable Tree Boosting System", venue: "KDD 2016", url: "#" },
    ],
    assignments: ["在 Kaggle 完成一个端到端比赛(银牌目标)", "实现 SVM 的 SMO 算法"],
    checklist: ["能解释 bias-variance tradeoff", "看到一个新数据集能给出 baseline 三步走"],
  },
  {
    id: "c302",
    code: "CS-302",
    moduleId: "m3",
    zh: "深度学习",
    en: "Deep Learning",
    credits: 9,
    weeks: 8,
    prereq: ["c301", "c204"],
    tag: "必修",
    goal: "把神经网络看成可微分编程;从 CNN 到 Transformer 的设计哲学。",
    outline: [
      "MLP · 反向传播 · 初始化",
      "卷积神经网络与归纳偏置",
      "RNN / LSTM / GRU",
      "Attention 与 Transformer",
      "正则化:Dropout · BN · LN",
      "Diffusion 模型基础",
    ],
    resources: [
      { type: "book", title: "Deep Learning · Goodfellow, Bengio, Courville", url: "#" },
      { type: "video", title: "NYU Deep Learning — LeCun & Canziani", url: "https://atcold.github.io/NYU-DLSP21/" },
    ],
    papers: [
      { title: "Attention Is All You Need", venue: "NeurIPS 2017", url: "#" },
      { title: "Deep Residual Learning for Image Recognition", venue: "CVPR 2016", url: "#" },
      { title: "Denoising Diffusion Probabilistic Models", venue: "NeurIPS 2020", url: "#" },
    ],
    assignments: [
      "从 numpy 开始重写 Transformer Encoder,在 PTB 上跑通",
      "复现 ResNet-18 在 CIFAR-10,达到 95%+",
      "实现一个最小可用的 DDPM",
    ],
    checklist: [
      "能用一段话向非技术朋友解释 attention",
      "知道为什么深网络需要残差连接",
      "理解 LN 在 Transformer 中放置位置的差异",
    ],
  },
  {
    id: "c303",
    code: "CS-303",
    moduleId: "m3",
    zh: "强化学习",
    en: "Reinforcement Learning",
    credits: 8,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "MDP · 价值函数 · 策略梯度 · 离线 RL · RLHF 的来龙去脉。",
    outline: [
      "MDP 与 Bellman 方程",
      "TD 学习 · Q-learning · SARSA",
      "策略梯度 · A2C · PPO",
      "Actor-Critic 与模型基础 RL",
      "离线 RL · 模仿学习",
      "RLHF 与对齐",
    ],
    resources: [
      { type: "book", title: "Reinforcement Learning: An Introduction · Sutton & Barto", url: "#" },
      { type: "video", title: "DeepMind × UCL RL Course", url: "#" },
    ],
    papers: [
      { title: "Proximal Policy Optimization Algorithms", venue: "Schulman et al., 2017", url: "#" },
      { title: "Training language models to follow instructions with human feedback", venue: "NeurIPS 2022", url: "#" },
    ],
    assignments: ["在 Atari 上跑通 DQN", "用 PPO 训练 MuJoCo 的 walker"],
    checklist: ["能区分 on-policy / off-policy", "解释 RLHF 的三阶段流水线"],
  },
  {
    id: "c304",
    code: "CS-304",
    moduleId: "m3",
    zh: "概率图模型",
    en: "Probabilistic Graphical Models",
    credits: 7,
    weeks: 6,
    prereq: ["c103"],
    tag: "选修",
    goal: "贝叶斯网络与马尔可夫随机场;精确与近似推断。",
    outline: ["有向图与无向图模型", "消息传递", "变分推断", "MCMC", "结构学习"],
    resources: [
      { type: "book", title: "Probabilistic Graphical Models · Koller & Friedman", url: "#" },
    ],
    papers: [
      { title: "Auto-Encoding Variational Bayes (VAE)", venue: "ICLR 2014", url: "#" },
    ],
    assignments: ["从零实现 VAE 在 MNIST 上", "用 Pyro 写一个层次贝叶斯模型"],
    checklist: ["能画出 VAE 的概率图", "理解变分下界为何叫「下界」"],
  },

  // ============ Module 4 ============
  {
    id: "c401",
    code: "CS-401",
    moduleId: "m4",
    zh: "自然语言处理",
    en: "Natural Language Processing",
    credits: 7,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "从 n-gram 到 BERT 到 LLM:语言建模史与现代任务范式。",
    outline: [
      "分词 · embedding · word2vec",
      "序列标注 · 解析",
      "Encoder-Decoder 与 BERT",
      "信息抽取 · 问答",
      "评测体系与数据集",
    ],
    resources: [
      { type: "video", title: "Stanford CS224N", url: "https://web.stanford.edu/class/cs224n/" },
      { type: "book", title: "Speech and Language Processing · Jurafsky & Martin", url: "#" },
    ],
    papers: [
      { title: "BERT: Pre-training of Deep Bidirectional Transformers", venue: "NAACL 2019", url: "#" },
      { title: "Distributed Representations of Words and Phrases (word2vec)", venue: "NeurIPS 2013", url: "#" },
    ],
    assignments: ["在 SQuAD 上微调 BERT 达到论文水平", "实现一个 BPE tokenizer"],
    checklist: ["对比 BPE / WordPiece / SentencePiece", "能解释 BERT 的 MLM 与 NSP 目标"],
  },
  {
    id: "c402",
    code: "CS-402",
    moduleId: "m4",
    zh: "计算机视觉",
    en: "Computer Vision",
    credits: 7,
    weeks: 7,
    prereq: ["c302"],
    tag: "必修",
    goal: "从经典几何到大模型时代;分类、检测、分割、生成的关键里程碑。",
    outline: [
      "图像形成 · 滤波 · 特征",
      "CNN 与现代 backbone",
      "检测与分割",
      "视频与多视图",
      "扩散模型与生成",
    ],
    resources: [
      { type: "video", title: "Stanford CS231N", url: "https://cs231n.stanford.edu/" },
    ],
    papers: [
      { title: "An Image is Worth 16x16 Words (ViT)", venue: "ICLR 2021", url: "#" },
      { title: "Segment Anything", venue: "ICCV 2023", url: "#" },
    ],
    assignments: ["复现 ViT-B/16 在 ImageNet-1k 子集上", "把 SAM 集成进一个标注工具"],
    checklist: ["对比 CNN 与 ViT 的归纳偏置", "理解为什么 detection 的 NMS 是必要的"],
  },
  {
    id: "c403",
    code: "CS-403",
    moduleId: "m4",
    zh: "大语言模型",
    en: "Large Language Models",
    credits: 9,
    weeks: 9,
    prereq: ["c401", "c303"],
    tag: "必修 · 旗舰",
    goal: "Scaling Laws · 预训练 · SFT · RLHF · 推理优化 · Agent。",
    outline: [
      "Scaling Laws 与数据配方",
      "预训练:架构与优化器",
      "SFT 与指令数据",
      "RLHF / DPO / 偏好对齐",
      "推理时:KV cache · speculative · MoE",
      "工具使用与 Agent",
      "评测:MMLU · HumanEval · Arena",
    ],
    resources: [
      { type: "video", title: "Stanford CS336 — Building LLMs from Scratch", url: "#" },
      { type: "video", title: "Andrej Karpathy — Zero to Hero", url: "https://karpathy.ai/zero-to-hero.html" },
    ],
    papers: [
      { title: "Scaling Laws for Neural Language Models", venue: "Kaplan et al., 2020", url: "#" },
      { title: "Training Compute-Optimal Large Language Models (Chinchilla)", venue: "NeurIPS 2022", url: "#" },
      { title: "LLaMA: Open and Efficient Foundation Language Models", venue: "2023", url: "#" },
      { title: "Direct Preference Optimization", venue: "NeurIPS 2023", url: "#" },
    ],
    assignments: [
      "从零预训练一个 ~100M 的 GPT-like(单 GPU,数小时)",
      "用 LoRA 微调一个 7B 模型完成指定任务",
      "实现一个带工具调用的 Agent loop",
    ],
    checklist: [
      "能徒手画出 Transformer 一次前向的 FLOPs",
      "解释 Chinchilla 的 token-per-param 比例",
      "知道 RLHF 与 DPO 在目标函数上的等价点",
    ],
  },
  {
    id: "c404",
    code: "CS-404",
    moduleId: "m4",
    zh: "AI 安全与对齐",
    en: "AI Safety & Alignment",
    credits: 5,
    weeks: 5,
    prereq: ["c403"],
    tag: "必修",
    goal: "从可解释性到对抗鲁棒,从对齐税到 scalable oversight。",
    outline: [
      "可解释性:probing · circuits",
      "对抗样本与红队",
      "RLHF 之外的对齐方法",
      "Scalable oversight",
      "评测与治理",
    ],
    resources: [
      { type: "video", title: "Anthropic — Alignment Research", url: "#" },
    ],
    papers: [
      { title: "Constitutional AI: Harmlessness from AI Feedback", venue: "2022", url: "#" },
      { title: "Toy Models of Superposition", venue: "Transformer Circuits Thread, 2022", url: "#" },
    ],
    assignments: ["对开源 7B 模型做一次红队报告", "复现一个 probing classifier"],
    checklist: ["能区分 capabilities 与 alignment 的边界", "理解 superposition 的几何直觉"],
  },
];

window.MODULES = MODULES;
window.COURSES = COURSES;
window.TOTAL_CREDITS = COURSES.reduce((s, c) => s + c.credits, 0);
window.TOTAL_WEEKS = COURSES.reduce((s, c) => s + c.weeks, 0);
